### ISSUE TITLE
Modifier Release Support (Wayland)

### ISSUE THREAD

**Issue by petrstepanov** [k0kubun/xremap#100]
Dear Takashi, I noticed unexpected behavior regarding the modifier key release. Below please find a minimal example of the issue. For instance, I would like the remapper to output a lowercase `b` when user presses `Shift-a`:

```
keymap:
  - name: Type lowercase `b` on Shift-a keypress
    remap:
      Shift-a: b
```

Currently when I run the above configuration file and press `Shift-a` in a text editor, the uppercase `B` is output. This is due to the fact that `Shift` modifier is "not released" and affects the output of a lowercase character `b` modifying it into a capitalized `B`.

Is there any plan to implement a release functionality. Off the top of my head, the config file could be extended as follows:

```
keymap:
  - name: Type lowercase `b` on Shift-a keypress
    remap:
      Shift-a: [{ release: Shift }, b]
```

Maybe one can come up with a more elegant syntax depending on the implementation. We have to take into account that sometimes there are two modifier keys (Shift-Control-KEY...) and both of them may need to be released. Let me know if this makes sense. Looking forward to hearing from you!

P.S. This functionality with modifier keys releasing is addressed in [Key Mapper](https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#combinations).
