### ISSUE TITLE
Allow esoteric keys like KEY_COPY

### ISSUE THREAD

**Issue by oblitzitate** [k0kubun/xremap#106]
I'm trying to remap special keys like `KEY_COPY` but it doesn't work.

```yml
keymap:
  - name: Kitty Copy
    remap: 
      copy: ctrl-shift-c
    application:
      only: kitty
```
