### ISSUE TITLE
How to handle vowel mutation (Umlauts)

### ISSUE THREAD

**Issue by razzeee** [k0kubun/xremap#120]
Hey,

I'm trying to migrate my `.Xmodmap`:

```
keycode  38 = a A a A adiaeresis Adiaeresis
keycode  39 = o O s S odiaeresis Odiaeresis
keycode  40 = e E d D EuroSign
keycode  41 = u U f F udiaeresis Udiaeresis
keycode  47 = s S semicolon colon ssharp U1E9E
```

I figured out this much (untested), but I don't see an obvious way to get Ä ä Ö ö Ü ü ß:
```
keymap:
  - name: Global
    remap:
      M-e: EURO
      M-E: EURO
```

**Comment by k0kubun** [comment]
Can you run xremap with RUST_LOG=debug like `RUST_LOG=debug xremap`, press each of Ä ä Ö ö Ü ü ß, and show the entire command output of `RUST_LOG=debug xremap`?

**Comment by razzeee** [comment]
I don't think that will work, as there are no keys for that, but I would like to map Alt + a to ä for e.g.

**Comment by k0kubun** [comment]
Do you know any way to input Ä ä Ö ö Ü ü ß without using .Xmodmap?

**Comment by razzeee** [comment]
I might be able to do that with some keyboard layouts I guess

**Comment by k0kubun** [comment]
If you can, please do. xremap transforms key events to key events, so you need to know what key events need to be generated. The easiest way to do that is to have an actual keyboard that can do that and capture its events.

If you can't, it might mean that you also rely on keyboard layout manipulation. If you use a keyboard that cannot input Ä ä Ö ö Ü ü ß, you'd need to find a keyboard layout that can input Ä ä Ö ö Ü ü ß and enable it, using configuration or another tool. Then, try capturing events to input those characters with that layout enabled.

**Comment by razzeee** [comment]
That does seem to work, but only as long as I keep that keyboard layout active :/

**Comment by k0kubun** [comment]
How about this idea? 

```yml
keymap:
  - name: Global
    remap:
      M-e:
        - { command: ["setxkbmap", "-layout", "something"] } # switch to a layout that can output euro
        - e # whatever key that can output euro with the layout
        - { command: ["setxkbmap", "-layout", "something"] } # switch back to a layout that you normally use
```

We currently have a `{ launch: xxx }` function, but it's meant to be used as a launcher and thus it doesn't wait for the command completion. `{ command: xxx }` shown above, on the other hand, is supposed to execute a command and wait for the completion synchronously. WDYT? If you think this works, I can implement it.

I'm just re-emphasizing this, but unlike xmodmap that works at an X keyboard level, xremap is by design implemented at a device level. The pros of that design is that it works for both X and Wayland, but if you implement it like xmodmap, then it doesn't work for Wayland. So that's a fundamental trade-off that xremap took. Unless we rewrite xremap, you have to use some other tool to deal with the X keyboard layer, and the above interface is the proposed integration from xremap.

**Comment by razzeee** [comment]
I guess that should work, but I'm not sure if you could fool that, if you type really fast. 

Realistically I'm just looking for a tool to modify my keyboard layout under wayland, similar to how I did it on X.

**Comment by k0kubun** [comment]
OK, got it. Let me close this and reopen this when I find a way to do that, but as of now I'm even not sure if it's feasible. If you do find one and let me know about the tool, I can take a look at the design and think about whether we can do the same thing in xremap or not, but for now, I don't know of one. Thank you for discussing this with me.

**Comment by codeluggage** [comment]
I read through this trying to figure out how to type Norwegian letters (æ, ø, å) on an English keyboard layout on Ubuntu, the same way that is standard on MacOS. Eventually got it working with the help of this answer (thank you!) and these links:

- The scan codes: https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L26-L572
- The compose key to get the desired result: https://en.wikipedia.org/wiki/Compose_key#Common_compose_combinations
- How to remap the compose key (for me to `Ctrl_R` - and, incidentally, moving the overlay key to show activities/search to `Insert`: `gsettings set org.gnome.mutter overlay-key "'Insert'"`): https://askubuntu.com/questions/70784/how-can-i-enable-compose-key#70788

And here it is, in all its beauty :) 

```
keymap:
  - name: Default
    remap:
      # Norwegian letters matching the MacOS use of Alt keys
      Alt-KEY_APOSTROPHE: [Ctrl_R, a, e] # æ
      Alt-Shift-KEY_APOSTROPHE: [Ctrl_R, A, E] # Æ
      Alt-o: [Ctrl_R, slash, o] # ø
      Alt-Shift-o: [Ctrl_R, slash, O] # Ø
      Alt-a: [Ctrl_R, o, a] # å
      Alt-Shift-a: [Ctrl_R, o, A] # Å
```

Hope this can prove useful for someone else trying to do the same!
