### ISSUE TITLE
can't remap tilde key

### ISSUE THREAD

**Issue by akhiljalagam** [k0kubun/xremap#126]
my config
```
keymap:
  - name: remap-keys
    remap:
      KEY_CapsLock: BTN_LEFT # capslock to left mouse click
      SHIFT_L-KEY_CapsLock: KEY_CapsLock # shift+capslock to capslock
      ALT_L-Esc: grave # alt+esc to grave
      SHIFT_L-Esc: asciitilde # shift+esc to tilde or asciitilde -> ~

```

when running this, i got this error
`Error: Failed to load config '/.xremap.yml': keymap[0].remap: data did not match any variant of untagged enum Actions at line 4 column 19`

also, tilde key is showing as KEY_GRAVE in debug logs.  

what's the correct key name for `~` ?
