### ISSUE TITLE
mouse button behaving like key

### ISSUE THREAD

**Issue by akhiljalagam** [k0kubun/xremap#127]
I remapped capslock to mouse left click button.

> xremap.yml

```
keymap:
  - name: remap-keys
    remap:
      KEY_CapsLock: BTN_LEFT # capslock to left mouse click
```
**issue**: unable to drag or select text.

When I hold capslock button it's repeating keystrokes. instead it should behave like mouse click which allows dragging and selecting text. Is it possible in xremap configuration?

**Comment by k0kubun** [comment]
That's fair. The current behavior is odd. I'll have a look.

**Comment by k0kubun** [comment]
Update: As I'm currently focusing on a big change for another OSS, I'm planning to work on this issue on Aug 13th. If I receive a pull request before that, I can take a look at that too.

**Comment by k0kubun** [comment]
I investigated this today. For this use case, please use `modmap` instead:

```yml
modmap:
  - name: remap-keys
    remap:
      KEY_CapsLock: BTN_LEFT # capslock to left mouse click
```

It's because, for `keymap`, we need to support generating more complex outputs like key sequences. To make key sequences functional, a key needs to be released before its next key is pressed. So release events are generated by design. We simply don't assume use cases of pressing a key for a while under `keymap`.

However, `modmap` works like it's replacing a physical key with another, emitting the event sequence like "repeat" as is. Because `modmap` works perfectly for your purpose, I don't see a motivation to support this under `keymap`. So please use `modmap`.
