### ISSUE TITLE
Support timeout_key on nested remap

### ISSUE THREAD

**Issue by kohane27** [k0kubun/xremap#128]
Hello @k0kubun. Hope you're doing well. Thank you for creating this awesome remap software. This is the only tool I find working reliably under Wayland and inside Wine!

However, I have trouble figuring out the config syntax. What I hope to acheive: `jk` is remapped to `KEY_ESC`; for a single `j` remapped to `KEY_DOWN`

I tried the following but it doesn't work:

```
keymap:
  - name: balabolka
    application:
      only: [balabolka.exe]
    remap:
      KEY_J:
        remap:
          KEY_K: KEY_ESC
          KEY_J: KEY_DOWN
```

The following works:

```
      KEY_J:
        remap:
          KEY_K:
            KEY_ESC
        timeout_millis: 150 # optional
```

But a single `KEY_J` will output the literal `j`, which is not what I want. I want a single `KEY_J` to output `KEY_DOWN`.

Any help is much appreciated. Thank you!

**Comment by k0kubun** [comment]
It seems like your use case is currently not implemented. Honestly, I haven't even thought of that.

To support that, a new syntax like this would be needed:

```yml
keymap:
  - name: balabolka
    application:
      only: [balabolka.exe]
    remap:
      KEY_J:
        remap:
          KEY_K:
            KEY_ESC
        timeout_key: KEY_DOWN # new
        timeout_millis: 150
```

As I'm currently focusing on a big change for another OSS, I'm planning to work on this issue on Aug 13th. If I receive a pull request before that, I can take a look at that too.
