### ISSUE TITLE
Modifier keys are not released on Wayland

### ISSUE THREAD

**Issue by davuses** [k0kubun/xremap#139]
Hi, I'm running xremap under wayland, for me it doesn't work in gnome gtk apps. There's no issue with qt based apps or others.

I'm using Nvidia graphic card, not sure if it's something to do with that.

I'm on Ubuntu22.04, gnome 42.2, Wayland, NVIDIA Driver Version: 510.73.05

The configuration file:
```
keymap:
  - name: Arrow-remap
    remap:
      SHIFT-ALT-KEY_H: KEY_LEFT
      SHIFT-ALT-KEY_L: KEY_RIGHT
      SHIFT-ALT-KEY_K: KEY_UP
      SHIFT-ALT-KEY_J: KEY_DOWN
```
