### ISSUE TITLE
I am not able to run xremap

### ISSUE THREAD

**Issue by Cruising0904** [k0kubun/xremap#148]
![image](https://user-images.githubusercontent.com/29267295/184631334-3e234f63-2ea9-4b8c-92de-cb4d29c84c63.png)

I was trying to run command ``` sudo xremap config.yaml ``` but the result like the picture
config.yaml contain #147  
```
virtual_modifiers:
  - CapsLock
modmap:
  - remap:
      CapsLock:
        held: CapsLock
        alone: Esc
keymap:
  - name: Global
    remap:
      CapsLock-i: Up
      CapsLock-j: Left
      CapsLock-k: Down
      CapsLock-l: Right
```

![image](https://user-images.githubusercontent.com/29267295/184632006-68ec8a20-fb14-4eb1-ae97-0809f0a491bc.png)
I also got this when I tried to reinstall

is there something I should do to work this ? Appreciate your hard work :) 

environment : Arch distro, sway
