### ISSUE TITLE
Trigger issue, with the latest update 0.7.5

### ISSUE THREAD

**Issue by cipherlogs** [k0kubun/xremap#154]
```
keymap:
  - name: Global
    remap:
      WIN-k: up
      WIN-j: down
      WIN-l: right
      WIN-h: left
      j:
        remap:
          k: Esc
          l: C-space
        timeout_millis: 100
```

I have been using this config for so long with no problems, but the latest update broke everything.

first now if I hit a combination so fast for example j-> s I will get `sj` which is not right.

second if for example I press a combination where it contains `Win-k` or `Win-j` etc ...
it will trigger them ??

`shift + win + k` will trigger `Win - k`
`ctrl + win + k` will trigger `win - k`
