### ISSUE TITLE
Modal support

### ISSUE THREAD

**Issue by cipherlogs** [k0kubun/xremap#156]
support for a modal system, just like vim
Normal mode, Insert mode, Visual mode, etc ...

there has been a branch that was merged already, but it is not working as expected when combined with nested remaps and `timeout_millis`

please refer to #93 
and refer to #154

example
```
keymap:
  # - name: Global
  - mode: insert
    remap:
      j:
        remap:
          j: {set_mode: normal}
          k: Esc
          l: C-space
        timeout_millis: 100

  - mode: normal
    remap:
      i: {set_mode: insert}
      h: Left
      l: Right
      k: Up
      j: Down
```

to trigger normal mode I have to go `jj` but it doesn't work
also I have tried to add nested remaps inside normal mode it doesn't work at all

I hope this feature doesn't die. if we can do a true vim like modal remapping that would be amazing.

**Comment by k0kubun** [comment]
> please refer to https://github.com/k0kubun/xremap/pull/93

It looks like you're doing something different from it. Did the example of https://github.com/k0kubun/xremap/pull/93 work in your environment? The attached config doesn't make sense because you didn't override `default_mode`. The default mode is "default_mode", so your YAML would enable no config by default. If it's not doing anything with the YAML, it's not a bug.

**Comment by k0kubun** [comment]
Please try this with v0.7.7:

```yml
default_mode: insert
keymap:
  - mode: insert
    remap:
      j:
        remap:
          j: {set_mode: normal}
          k: Esc
          l: C-space
        timeout_millis: 500

  - mode: normal
    remap:
      i: {set_mode: insert}
      h: Left
      l: Right
      k: Up
      j: Down
```

It seems to be working fine. Please provide a key sequence example if you have a case that doesn't work as you expect.
