### ISSUE TITLE
Application-specific overrides

### ISSUE THREAD

**Issue by berwynhoyt** [k0kubun/xremap#163]
Application-specific remapping doesn't seem to be designed quite for my use-case. But I've found a workaround.

I have a key map (you have seen my "wordstar keymap" #162) that works fin for most apps, but certain keys don't work right in specific apps. I'd like to fix this. The following will work, at the cost of HUGE amounts of repeated mappings. Here is a minimal example, but you can see where it would end up, even with as few as 4 or 5 overrides:

```
keymap:
  - name: Wordstar
    remap:
      CapsLock-t: C-delete
      # 50 other remappings

  - name: libreoffice-writer-overrides
    application:
      only: libreoffice-writer
    remap:
      CapsLock-t: [C-delete, delete]
```

The override doesn't work as an override. However, by trial and error I discovered a workaround: it works if I move the default "Wordstar" mapping to the end. It might be helpful to document this as the required order seems slightly counterintuitive to me.

I am content with the workaround, but a nice-to-have would be a slightly different override syntax:

```
keymap:
  - name: Wordstar
    remap:
      CapsLock-t:
        default: C-delete
        application:
          { libreoffice-writer: [C-delete, delete] }
          { other-app: [C-delete, delete] }
```

What do you think?

I realize that you're busy this week. Don't worry: this can wait.

**Comment by k0kubun** [comment]
Similar to https://github.com/k0kubun/xremap/issues/162, let me get back to this next week or so. Thank you.

**Comment by berwynhoyt** [comment]
The above is a nice-to-have, but the following is more necessary since the workaround doesn't work for it. The workaround doesn't work for second-level keys. I present a cut-down but still realistic example below.

The following key map defines prefix key CapsLock-q (a wordstar standard prefix key). As shown, I can override non-prefixed keys for specific apps by putting them first in the yml file. But I can't override prefixed keys without disabling all the other standard prefixed keys for that app. So when I redefine ^QY for Ferdium app, it makes all the following stop working in Ferdium: ^QS, ^QD, ^QR, ^QC, ^QA, ^QF (where ^ = CapsLock).

```
# Minimal test to show the difficulty of overriding second-level keys

virtual_modifiers:
  - CapsLock

keymap:
  # ~~~~ app-specific overrides must go first before the default key definitions
  - name: override-ferdium-quirks
    application:
      only:
        - ferdium.Ferdium
    remap:
      # override 1st-level key for specific app -- works
      CapsLock-f: [{with_mark: C-right}, {with_mark: right}]
      CapsLock-q:
        # Generic ^QY definition below doesn't work properly in Ferdium, so replace with a different definition
        remap:
          CapsLock-y: [{set_mark: false}, Shift-end, space, backspace]

          # ***PROBLEM***: All other CapsLock-q prefixed keys now stop working


  # ~~~~ Now for the main key definitions
  - name: Main-Wordstar-Keys
    remap:
      CapsLock-s: {with_mark: left}
      CapsLock-d: {with_mark: right}
      CapsLock-e: {with_mark: up}
      CapsLock-x: {with_mark: down}

      CapsLock-q:
        remap:
          CapsLock-y: [{set_mark: false}, Shift-end, C-x]  # Cut to end of line

          CapsLock-s: {with_mark: home}
          CapsLock-d: {with_mark: end}
          CapsLock-r: {with_mark: C-home}
          CapsLock-c: {with_mark: C-end}
          CapsLock-f: [{set_mark: false}, C-f]  # find
          CapsLock-a: [{set_mark: false}, C-h]  # replace
```

**Comment by k0kubun** [comment]
> I discovered a workaround: it works if I move the default "Wordstar" mapping to the end. It might be helpful to document this as the required order seems slightly counterintuitive to me.

What do you think about this config?

```yml
keymap:
  - remap:
      CapsLock-t: C-delete
  - remap:
      CapsLock-t: [C-delete, delete]
```

You can't understand the author's intention, right? This is the kind of thing that your config is doing. I think this is what you actually wanted to write:

```yml
keymap:
  - name: Wordstar
    application:
      not: libreoffice-writer
    remap:
      CapsLock-t: C-delete
  - name: libreoffice-writer-overrides
    application:
      only: libreoffice-writer
    remap:
      CapsLock-t: [C-delete, delete]
```

Ideally, xremap should validate configs and reject what you wrote, for example testing each application name mentioned in non-regexp matchers. But either way, I don't think it's a good idea to have multiple remappings for the same key combination at the same level. Only nested remaps for overrides should cause a conflict.

> the following is more necessary since the workaround doesn't work for it.

Can you file a different issue if it's a different problem? It's nice that you provided a working configuration, but can you also consider minimizing it a bit, show steps to test the behavior you want to fix, and explain the expected and actual behaviors? This problem seems fairly complicated, so I need your help to understand it.

**Comment by berwynhoyt** [comment]
Hi Takashi. Thanks for taking the time to look at this. I'll try to explain better.

The problem need is conceptually very simple: there needs to be _specific_ key overrides in specific apps. Currently there is only a way to override the whole map, not specific keys.

To make it specific, C-Right (word-right) does a different thing in different apps under linux. In most editors, it moves to the next word (after the space) But in a few apps it moves to the end of the current word (before the space). Hence, my Wordstar mapping for word-right needs to have overrides for these few apps.

Say I have a generic key map of 50 keys. Then for a few apps I want to override just the definition of, say, `CapsLock-t`. Using your suggested example of `not: libreoffice-writter` doesn't work because then all 50 key definitions (which are under `not:`) won't work under `only:`. In reality, I want, say, 47 of them to work in every app, 3 of them to have an alternate definition in libreoffice-writer (and 5 other specific apps), and 50 of them to work in non-libreoffice apps. Yes, I could split them out into 3 different sections, but it gets extremely unweildy when you have several other apps also wanting to override a selection of keys. And it wouldn't work at all when you have double-key mappings (see below).

Far better to have an override -- which is exactly what I have, by putting the 'generic' key set last. It works.

Except it doesn't work for double-key mappings. I hesitate to move this to a new issue because the problem/solutions are so closely related, that a solution for the single-key problem must also work for double-key maps. However, I will explain the remaining problem (double-key sequences) in a new comment.

**Comment by k0kubun** [comment]
I started to get what you were saying. You want to define 50-ish default mapping and override a few of them for each of the 5 applications, right?

Currently, overriding another remap can happen only at a nested remap. It feels like you're proposing a feature that lets an `application` filter increase the priority over remaps that don't have one. I can live with that change, but even if we introduce it, there's no way to properly reconcile the priority between multiple entries without relying on ordering. For example,

```yml
keymap:
  - application:
      only: [app1, app2]
    remap:
      C-a: C-b
  - application:
      only: [app2, app3]
    remap:
      C-a: C-c
```

When you're using "app2", you go back to the same problem; there's no way to semantically differentiate their priority if you ignore their ordering. We can never drop ordering as a priority measure.

If we need to keep ordering anyway, to keep xremap simple, is it an acceptable solution to just document the behavior and use it, i.e. put lower priority items later? I could also just reverse the remap entry traversal if you want to put lower priority entries earlier if that makes sense.
