### ISSUE TITLE
Normal key as modifier for press/hold

### ISSUE THREAD

**Issue by Liu233w** [k0kubun/xremap#164]
Currently, I have a keyboard with a custom key set to `F19`, and I want to use it as left ctrl when hold and ESC when press then release. But it seems to not work.

I have following configs:
```
virtual_modifiers:
  - F19

modmap:
  - name: Special mapping F19 to ESC/Ctrl
    remap:
      KEY_F19:
        held: KEY_LEFTCTRL
        alone: KEY_ESC
        alone_timeout_millis: 1000
```

So is this feature supported or there are some issue in my config?
