### ISSUE TITLE
Key press / release is too fast for gnome-terminal

### ISSUE THREAD

**Issue by timbertson** [k0kubun/xremap#179]
I just started using xremap over xbindkeys and I love it, but I noticed one issue. I think the fault is in gnome-terminal, because other apps (chrome, firefox, nautilus) are fine. I have the following setup:

```
keymap:
  - name: Tab shifting
    remap:
      LEFTCTRL-SHIFT-RIGHTBRACE: LEFTCTRL-PAGEDOWN
      LEFTCTRL-SHIFT-LEFTBRACE: LEFTCTRL-PAGEUP
```

This gives me mac-style shortcuts for switching tabs.

Unfortunately it doesn't work in gnome-terminal or tilix (so it might be a bug in the underlying vte). They don't seem to register the combination, they just end up scrolling up/down or inserting some escape characters into the terminal.

I found that adding a tiny sleep here makes it work:

```
diff --git src/event_handler.rs src/event_handler.rs
index f1d2267..369e753 100644
--- src/event_handler.rs
+++ src/event_handler.rs
@@ -343,6 +343,7 @@ impl EventHandler {
 
         // Press the main key
         self.send_key(&key_press.key, PRESS)?;
+        std::thread::sleep(std::time::Duration::from_millis(20));
         self.send_key(&key_press.key, RELEASE)?;
 
         // Resurrect the original modifiers
```

Obviously this a is dumb workaround and not xremap's fault, but would you be open to a PR which added some kind of `keypress_duration` config which controlled whether we do a short sleep between pressing and releasing the key?

**Comment by k0kubun** [comment]
Just to have more contexts, are you using X11 (not Wayland)?

**Comment by timbertson** [comment]
I'm using wayland:

```
$ echo $XDG_SESSION_TYPE
wayland
```

I'm running gnome-shell 42.5, fedora 36. I don't see any `xwayland` or `x11` processes running. There is an `/usr/libexec/ibus-x11` process running, but I don't know if that's relevant.

**Comment by k0kubun** [comment]
I've seen a similar behavior on Wayland and I feel it's relevant. Just to be sure about it, can you test the same thing on X11? 

Wayland has a lot of issues and I'm currently investigating how we could work around them. If this is one of such instances, I'd like to introduce the workaround after confirming that this is indeed the limitation of Wayland.

**Comment by timbertson** [comment]
Tested on x11, and it works fine there without the additional sleep. So yes it seems like a wayland thing.

**Comment by benhoyt** [comment]
I had a very similar issue (Ubuntu 22.04 amd64, Gnome, Wayland), and @timbertson's patch worked for me too, thanks!

**Comment by kzys** [comment]
I can reproduce the issue @timbertson has reported. On my laptop (Framework Laptop 12th gen), sleeping 3 seconds works, but sleeping 2 seconds doesn't. Not really sure this is depending on the hardware or not.

I'm unsure that is coming from libinput, a Wayland compositor or something else.

I can open a PR to "fix" the issue by introducing `keypress_duration` or auto-detect Wayland and sleep a bit. Would it work?

**Comment by k0kubun** [comment]
At this point, I'm okay with temporarily introducing the config, which I might remove once I find a way to fix the root cause. I'll accept a patch if any of you files that.

**Comment by kzys** [comment]
Hmm, I accidentally put the delay right before `self.send_keys(&missing_modifiers, RELEASE)?;` and it worked fine...

**Comment by k0kubun** [comment]
Released the workaround as v0.7.6.

**Comment by thorrr** [comment]
Can you provide an example of where to put the `keypress_delay_ms` modifier?  None of the following seem to work:

```yaml
  - name: Tab shifting
    remap:
      LEFTCTRL-SHIFT-RIGHTBRACE: LEFTCTRL-PAGEDOWN
      LEFTCTRL-SHIFT-LEFTBRACE: LEFTCTRL-PAGEUP
    keypress_delay_ms: 20
```
Output:
```sh
Error: Failed to load config 'config.yml': keymap[3]: unknown field `keypress_delay_ms`, expected one of `name`, `remap`, `application`, `mode` at line 45 column 5
```


```yaml
  - name: Tab shifting
    remap:
      LEFTCTRL-SHIFT-RIGHTBRACE: LEFTCTRL-PAGEDOWN
      LEFTCTRL-SHIFT-LEFTBRACE: LEFTCTRL-PAGEUP
      keypress_delay_ms: 20
```

Output:
```sh
Error: Failed to load config 'config.yml': keymap[3].remap: unknown key 'keypress_delay_ms' at line 43 column 7
```

```yaml
  - name: Tab shifting
    remap:
      LEFTCTRL-SHIFT-RIGHTBRACE: LEFTCTRL-PAGEDOWN
      LEFTCTRL-SHIFT-LEFTBRACE: LEFTCTRL-PAGEUP
        keypress_delay_ms: 20
```

Output:
```sh
Error: Failed to load config 'config.yml': keymap[3].remap: data did not match any variant of untagged enum Actions at line 43 column 7
```

**Comment by k0kubun** [comment]
I believe it's top-level, no indentation.

**Comment by thorrr** [comment]
Thanks!  This worked.  For reference:

```yaml
keypress_delay_ms: 20

modmap:
  - name: Global
    <....>

keymap:
  - name: Global
    <.....>

```
