### ISSUE TITLE
trigger issue 0.7.7.1

### ISSUE THREAD

**Issue by cipherlogs** [k0kubun/xremap#197]
related to #154 

for example 

shift + win + k will trigger Win - k (which is up in my config)
ctrl + win + k will trigger win - k (which is up in my config)

```
keymap:
  - name: Global
    remap:
      WIN-k: up
```
