### ISSUE TITLE
Overrides do not work with multi-key (nested) sequences

### ISSUE THREAD

**Issue by berwynhoyt** [k0kubun/xremap#199]
Per pull-request #198 it is now possible to override specific keys of a generic keymap for spec apps. However this override only words for single-level keys, not for 2-key sequences.

```
virtual_modifiers: CapsLock
keymap:
  # app-specific overrides must go here before the default key definitions or they do nothing
  - name: override-whatsapp-web-quirks
    application:
      only: Google-chrome
    remap:
      CapsLock-f: [C-right, right]
      CapsLock-q:
        remap:
          CapsLock-y: [{set_mark: false}, Shift-end, space, backspace]

  - name: Main-Wordstar-Keys
    remap:
      CapsLock-f: C-right
      CapsLock-s: {with_mark: left}
      CapsLock-d: {with_mark: right}

      CapsLock-q:
        remap:
          CapsLock-y: [{set_mark: false}, Shift-end, C-x]

          CapsLock-s: {with_mark: home}
          CapsLock-d: {with_mark: end}
```

Result:
1. Capslock-f works find in every app, and it is overridden fine in Google-chrome. Good.
1. Capslock-s and Capslock-d work fine in every app and also work in Google-chrome as intended. Good.
1. Capslock-qy overrides and works fine in Google-chrome. Good
1. But although Capslock-qs and Capslock-qd work in most apps, they do nothing in Google-chrome. _**Bad**_.

Now, with such a simple example, you can make it work using duplication of definitions. But my real
example has many more 2-level keys mapped. And a few specific ones need to be overridden by each different app.

Without knowing how xremap works internally (I don't know Rust), I'm guessing that xremap would have to retain the complete multi-key sequence until it was entirely resolved, and at each keypress look up the entire sequence in each multi-key tree.

There is a workaround by duplicating the full 2nd-level maps for each app. So this is a nice-to-have rather than a need-to-have.
