### ISSUE TITLE
[Feature request] Import files in config

### ISSUE THREAD

**Issue by ChingChang9** [k0kubun/xremap#202]
It would be nice if we could import files in a config file to reduce duplication. Here's an idea of the syntax:
```yml
import:
  - name: application-specific
    file1.yml # the extension is optional
    file2     # imports file2.yml

modmap:
  ...

keymap:
  ...
```

This would be useful for people who have keyboards with different layouts. For example, I have a MacBook Air keyboard where the mod key is between the space and alt key, and a wireless keyboard where the mod and alt keys are swapped.
I have a config file for each device, where the keymaps are the same. The two files differ only by their modmap.
Being able to import files would allow me to factor out the common keymaps instead of having to apply the same changes to both files.
