### ISSUE TITLE
Defining `<Super>f` mapping affects the behavior of `<Super><Control>f`

### ISSUE THREAD

**Issue by ueaner** [k0kubun/xremap#210]
Hello, Thank you for your great work.

I used gsettings to define a shortcut for `toggle-fullscreen` as `<Super><Control>f`. work well.
```sh
$ gsettings get org.gnome.desktop.wm.keybindings toggle-fullscreen
['<Super><Control>f']
```

Then mapped `<Super>f` to `<Control>f` in the xremap.yml:
```yml
keymap:
  - name: basic
    remap:
      Super-f: C-f              # Find
```

Now `<Super><Control>f` shortcut key does not trigger the behavior of `toggle-fullscreen`, but shows the behavior of `<Control>f`.

How to make them coexist?
