### ISSUE TITLE
Trigger a key sequence, keeping modifiers

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/xremap#218]
```
keymap:
  - remap:
      a:
        - Ctrl-Shift-u
        - Ctrl-Shift-2
        - Ctrl-Shift-0
        - Ctrl-Shift-a
        - Ctrl-Shift-c
```

This holds and releases Ctrl and Shift for each action, but it neds to be held during the entire sequence to make it input a Unicode character in some environments.

original: https://www.reddit.com/r/Ubuntu/comments/rmqm5m/comment/j15xlju/?utm_source=reddit&utm_medium=web2x&context=3
