### ISSUE TITLE
`--watch=config` Reloading Config causes key mapping to stop working

### ISSUE THREAD

**Issue by DavidPD** [k0kubun/xremap#221]
I'm running into an issue where I'm trying to use the `--watch=device,config` option and whenever I change the config file I get the message "Reloading Config" from XRemap, but then it just stops remapping keys and I have to restart it manually. At first I thought maybe this only happened if I had a configuration error, but then I checked and it stops working even if I start xremap and immediately save the config file without any changes.

I'm trying to use systemctl to run xremap on startup, but this issue also appears even if I run it with `sudo` from a terminal.

For now my workaround is just to run xremap without hot-reloading, and restart it manually whenever I'm making changes.

## System Info

- xremap 0.7.15
- Pop!OS 22.04
- Command I'm using to run xremap: `/home/me/.cargo/bin/xremap /home/me/.config/xremap/config.yml --watch=device,config`

## config file

```
modmap:
  - name: Global
    remap:
      Super_L: Ctrl_L
      Ctrl_L: Super_L
keymap:
  - name: Terminal
    application:
      only: Gnome-terminal
    remap:
      Super-c: C-c
```
