### ISSUE TITLE
Number keys (without modifier keys, at least) are not working without `KEY_` prefix

### ISSUE THREAD

**Issue by ihor-oleks** [k0kubun/xremap#231]
Next keymap is not working:

```yaml
keymap:
  - name: Symbols
    exact_match: true
    remap:
      Alt-Minus:
        - Ctrl-Shift-U
        - 2
        - 0
        - 1
        - 3
        - Enter
```

However, this one works:

```yaml
keymap:
  - name: Symbols
    exact_match: true
    remap:
      Alt-Minus:
        - Ctrl-Shift-U
        - KEY_2
        - KEY_0
        - KEY_1
        - KEY_3
        - Enter
```

**Comment by k0kubun** [comment]
We could make it work, but it's more about how YAML works. You could do:

```yaml
keymap:
  - name: Symbols
    exact_match: true
    remap:
      Alt-Minus:
        - Ctrl-Shift-U
        - '2'
        - '0'
        - '1'
        - '3'
        - Enter
```

which is at least without `KEY_`. But I guess you don't want to quote them either?
