### ISSUE TITLE
xremap turns Control into CapsLock?

### ISSUE THREAD

**Issue by atsaloli** [k0kubun/xremap#233]
Hello.  I just tried xremap.  I used this simple config:

```
keymap:
  - name: test
    remap:
      C-b:
        launch: ["bash", "-c", "echo hello > /tmp/test"]
    application:
      only: Google-chrome
```

The mapping works fine; but when I press the left Control key in my terminal, my CapsLock key lights up and e.g., Ctrl-C gives me a capital C.

Could you please help me understand what's going on and how I would troubleshoot this?

xremap 0.8.0 on q4os 4.11 (www.q4os.org -- v4.11 is based on Debian 11 (bullseye))
