### ISSUE TITLE
Is it possible remap key sequence Ctrl, 1 to Ctrl+1?

### ISSUE THREAD

**Issue by atsaloli** [k0kubun/xremap#234]
Hello,

Excited to try xremap.

Is it possible to remap the key sequence of "Control", "1", to Ctrl+1?  (For switching tabs in the Web browser.)

How about "," and "1" to Ctrl+1?  (Using comma as a "leader key" of sorts.)

Thanks!
-at

**Comment by k0kubun** [comment]
> Is it possible to remap the key sequence of "Control", "1", to Ctrl+1? (For switching tabs in the Web browser.)

Incorporating a modifier key as part of a key sequence is not directly supported. As a workaround, however, I think you could emit another key (which should be no-op on your environment) when Ctrl is not held and use that as part of the sequence, e.g.

```yml
modmap:
  - remap:
      Ctrl_L:
        alone: macro
        held: Ctrl_L
keymap:
  - remap:
      macro:
        remap:
          '1': Ctrl-1
```

> How about "," and "1" to Ctrl+1? (Using comma as a "leader key" of sorts.)

This is directly supported. You can use:

```yml
keymap:
  - remap:
      comma:
        remap:
          '1': Ctrl-1
```

**Comment by atsaloli** [comment]
Thanks, @k0kubun !

I have this in my .bash_profile to turn CapsLock into Control: ` setxkbmap -option; setxkbmap -option "ctrl:nocaps"`

And this is my xremap.yaml:

```
keymap:
  - name: 'Remap sequence comma 1 to Ctrl+1 for switching tabs in Chrome'
    remap:
      comma:
        remap:
          '1': Ctrl-1
    application:
      only: Google-chrome
  - name: 'Remap sequence comma 2 to Ctrl+2 for switching tabs in Chrome'
    remap:
      comma:
        remap:
          '2': Ctrl-2
    application:
      only: Google-chrome
```

When I press "comma" and then "1" (or "2") in Chrome, it doesn't switch tabs, but my CapsLk key on my keyboard lights up, and when I type anything, it comes out uppercase.  When I enter the key sequence , 1 again, CapsLk turns off.

I tried running  ` setxkbmap -option` to clear all remappings there and then I ran xremap and I noticed when I press Ctrl key that it turns on CapsLock.  Any ideas how to troubleshoot this further, please?
