### ISSUE TITLE
virtual modifier become unstable with shift key

### ISSUE THREAD

**Issue by takatu-kazusige** [k0kubun/xremap#237]
Virtual modifier seems to become unstable, when it is used with shift key.
To be more specific, I set KATAKANAHIRAGANA as virtual modifier, and it functions as expected. But with shift key, some remaps does not work, and after restarting xremap the remap that does not work may change.

<part of config.yml>
virtual_modifiers:
  - KATAKANAHIRAGANA
keymap:
  - remap:
      W: L
      E: J
      R: F
      T: C
      KATAKANAHIRAGANA-Q: [E, K]
      KATAKANAHIRAGANA-W: [U, K]
      KATAKANAHIRAGANA-E: [I, K]
      KATAKANAHIRAGANA-R: [A, K]
      KATAKANAHIRAGANA-T: [O, K]
[config-vm.yml.txt](https://github.com/k0kubun/xremap/files/10547088/config-vm.yml.txt)

<behavior>
Without shift key every remap works correctly.
qwert -> ekukikakok
But with shift key, some remap does not work.
qwert -> EKLIKAKOK
And after restarting xremap, the remap which does not work may change.
qwert -> EKUKIKAKC

**Comment by k0kubun** [comment]
I kind of suspect recent contributions broke it. Could you try some past versions and check if an old version works? If it works, could you find the first version that broke it?

**Comment by takatu-kazusige** [comment]
Thank you for your reply.
I've tried following versions. But they seems to be showing the same behavior. In addition, v.0.7.0 seems not to accept shift key.
```
[v0.8.0]
vm         : ekukikakok
vm + shfit : EKUKIKAKC

[v0.7.7]
vm         : ekukikakok
vm + shfit : EKLJAKC

[v0.7.3]
vm         : ekukikakok
vm + shfit : EKLIKFOK

[v0.7.0]
vm         : ekukikakok
vm + shfit : eklikfok
```

**Comment by k0kubun** [comment]
> But they seems to be showing the same behavior.

I'm kind of confused since all of these examples seem to show different behavior. Do you mean none of 0.8.0, 0.7.7, 0.7.3, and 0.7.9 was the intended behavior? What is the expected output for `vm + shift`?

**Comment by takatu-kazusige** [comment]
Thank you for your reply.

The expected output during the `vm + shift` is `EKUKIKAKOK`, which is the same as the output when only `vm` is pressed (`ekukikakok`), with all characters transformed to uppercase. In reality however, some keys may be remapped as if the "vm" key is not pressed and the keys not working correctly may change if the program is restarted. Despite variations in the output, the pattern of incorrect behavior remains unchanged.

**Comment by k0kubun** [comment]
Thank you for confirming it.

I'm guessing that virtual modifiers are not working correctly when the keymap is not exactly matching, while the same thing works for non-virtual modifiers.

As a workaround, I think something like the following config might work as you expect:

```yml
virtual_modifiers:
  - KATAKANAHIRAGANA
keymap:
  - remap:
      W: L
      E: J
      R: F
      T: C
      KATAKANAHIRAGANA-Q: [E, K]
      KATAKANAHIRAGANA-W: [U, K]
      KATAKANAHIRAGANA-E: [I, K]
      KATAKANAHIRAGANA-R: [A, K]
      KATAKANAHIRAGANA-T: [O, K]
      Shift-KATAKANAHIRAGANA-Q: [Shift-E, Shift-K]
      Shift-KATAKANAHIRAGANA-W: [Shift-U, Shift-K]
      Shift-KATAKANAHIRAGANA-E: [Shift-I, Shift-K]
      Shift-KATAKANAHIRAGANA-R: [Shift-A, Shift-K]
      Shift-KATAKANAHIRAGANA-T: [Shift-O, Shift-K]
```

However, this should obviously be just fixed instead of using the above workaround. Would you be interested in working on a pull request to fix it?
