### ISSUE TITLE
Different mapping if 'held' or 'alone' - Timeout modifier not working as intended?

### ISSUE THREAD

**Issue by neophrema** [k0kubun/xremap#238]
Hello,
thank you very much for this program, i was looking for this for a long (!) time.

I am using QMK on my external keyboard and I have mapped "F" and "J" to be registered as Shift, if I hold these keys instead of just typing. (This is due to my pinkies hurting).
I found the same functionality in xremap, but I can't use it due to timing issues.

```

modmap:
  - name: ShiftF 
    remap: 
      KEY_F:
        held: SHIFT_R
        alone: KEY_F
      # alone_timeout_millis: 10000 # Optional

```

I'm not sure if this is a feature request or a bug complain.

If I'm typing the word: "jelly"
It registers          "Elly"

1.) I think it should be specified how long the key has to be pressed, before it gets registered as held.
1.2) Is there a variable "held_timeout_millis"?

2.) I do not understand how "alone_timeout_millis" works.
2.1)I played with different values and it seems like xremap cap these values, correct?
2.2)Im not sure if the variable name - "(alone_)timeout(_millis)" -  might be ambiguous.

I think it would be ideal if I could set the time that the button needs to be pressed, e.g. 3 sec, before it acts as a modifier, before that its just an "f".
I understand that I have a rare user case, yet I suspect that there *could* be an issue with the code.

Hopefully this might be interesting for others as well.
neophrema
