### ISSUE TITLE
Can I change keyboard layout with this tool ?

### ISSUE THREAD

**Issue by nurmohammed840** [k0kubun/xremap#263]
I am trying to map number key (`1234567890`) into symbol (`!@#$%^&*()`)

My `config.yml` look like this:

```yml
modmap:
  - name: Nboard+
    remap:
      CapsLock		: Enter
      
keymap:
  - name: keyboard layout
    remap:
       KEY_1		: Shift-KEY_1 		# 1 -> !
       Shift-KEY_1	: KEY_1			# ! -> 1
```

But this doesn't shift number `1`  into `!`
