### ISSUE TITLE
Question: How to map alt+click as ctrl+click

### ISSUE THREAD

**Issue by zaaom** [k0kubun/xremap#267]
Hello, Thanks @k0kubun and contributors for the great work and speedy support! :clap: 

Coming from mac, i wanted to open links in new tabs when i click with `alt` held, i tried different configs using modmap and keymap, but either it doesn't take effect or the mouse freezes.

#### with modmap: 
- works as `ctrl` in general, so with that
  - i lose `alt+tab` function
  - mouse scroll button freezes
 
```yml
modmap:
  - remap:
      KEY_LEFTALT: KEY_LEFTCTRL
    application:
      only:
        - Brave-browser
```

#### with keymap: doesn't take any effect
```yml
keymap:
  - remap:
      Alt-BTN_LEFT: ctrl-BTN_LEFT
```

is something wrong with my config? or this behavior cannot be remapped?
Thank you!
