### ISSUE TITLE
Is It possible to use if condition in remap 

### ISSUE THREAD

**Issue by Yunuuuu** [k0kubun/xremap#271]
Hi, thanks for the great keybinding remapping tool which bring lots of conveniences.

After reading documents, I didn't find a way to do conditional process, is It possible to use if condition in remap like this?
```
if TRUE: do something
  else: do another thing
```

**Comment by Yunuuuu** [comment]
Maybe a nested mode?
```
      CapsLock-space: 
        - mode: mark
          remap: [{ set_mark: false }, { set_mode: default }]
        - mode: default
          remap: [{ set_mark: true }, { set_mode: mark }]
```

**Comment by Yunuuuu** [comment]
Thanks for your reply, following your advice I have tried follows:
```
# https://github.com/k0kubun/xremap/blob/master/example/emacs.yml
# echo $XDG_SESSION_TYPE
keypress_delay_ms: 10

virtual_modifiers:
  - CapsLock

keymap:
  - name: Emacs
    exact_match: true
    remap:
      # following use marks
      # Cursor
      CapsLock-b: { with_mark: left }
      CapsLock-f: { with_mark: right }
      CapsLock-p: { with_mark: up }
      CapsLock-n: { with_mark: down }
      # Beginning/End of line
      CapsLock-a: { with_mark: home }
      CapsLock-e: { with_mark: end }
      # Forward/Backward word
      ALT_L-b: { with_mark: C-left }
      ALT_L-f: { with_mark: C-right }
      # Forward/Backward Paragraph
      ALT_L-p: { with_mark: C-up }
      ALT_L-n: { with_mark: C-down }
      # Beginning/End of file
      ALT_L-comma: { with_mark: C-home }
      ALT_L-dot: { with_mark: C-end }
      # Page up/down
      ALT_L-v: { with_mark: pageup }
      CapsLock-v: { with_mark: pagedown }
      # folowing reset marks
      # Copy
      CapsLock-w: [C-x, { set_mark: false }]
      ALT_L-w: [C-c, { set_mark: false }]
      CapsLock-y: [C-v, { set_mark: false }]
      # Delete Forward/Backward character
      CapsLock-d: [delete, { set_mark: false }]
      CapsLock-h: [BACKSPACE, { set_mark: false }]
      # Delete Forward/Backward word
      ALT_L-d: [C-delete, { set_mark: false }]
      ALT_L-h: [C-BACKSPACE, { set_mark: false }]
      # Kill before line
      CapsLock-u: [Shift-home, C-x, { set_mark: false }]
      # Kill after line
      CapsLock-k: [Shift-end, C-x, { set_mark: false }]
      # transpose characters
      CapsLock-t: [Shift-left, C-x, right, C-v, {set_mark: false}]
      ALT_L-t: [Shift-right, C-x, left, C-v, left, {set_mark: false}]
      # Undo
      CapsLock-slash: [C-z, { set_mark: false }]

      # Newline
      # CapsLock-m: enter
      CapsLock-j: enter
      # Openline
      CapsLock-o: [end, enter]
      # C-Shift-ro: C-z
      # Search
      CapsLock-s: F3
      CapsLock-r: Shift-F3
      # M-Shift-5: C-h

      # Kill buffer
      CapsLock-q: [C-f4, { set_mark: false }]

      # Cancel
      KEY_ESC: [KEY_ESC, { set_mark: false }]

      # keybindings for flameshot
      KEY_F3: 
        launch: ["flameshot", "gui", "--clipboard", "-s"]
      CTRL_L-KEY_F3: 
        launch: ["flameshot", "gui", "--clipboard"]
      KEY_F4: 
        launch: ["flameshot", "gui", "--clipboard", "--pin", "-s"]
      CTRL_L-KEY_F4: 
        launch: ["flameshot", "gui", "--clipboard", "--pin"]
  - mode: mark
    CapsLock-space: [{ set_mark: false }, {set_mode: no_mark} ]
  - mode: no_mark
    CapsLock-space: [{ set_mark: true }, {set_mode: mark}]

default_mode: no_mark
```
Above incur errors: 
```
✗ /opt/xremap/xremap-x11 ~/.xremap
Error: Failed to load config '/home/yun/.xremap': keymap[1]: unknown field `CapsLock-space`, expected one of `name`, `remap`, `application`, `mode`, `exact_match` at line 81 column 5
```
So I change the config to follows:
```
# https://github.com/k0kubun/xremap/blob/master/example/emacs.yml
# echo $XDG_SESSION_TYPE
keypress_delay_ms: 10

virtual_modifiers:
  - CapsLock

keymap:
  - name: Emacs
    exact_match: true
    remap:
      # following use marks
      # Cursor
      CapsLock-b: { with_mark: left }
      CapsLock-f: { with_mark: right }
      CapsLock-p: { with_mark: up }
      CapsLock-n: { with_mark: down }
      # Beginning/End of line
      CapsLock-a: { with_mark: home }
      CapsLock-e: { with_mark: end }
      # Forward/Backward word
      ALT_L-b: { with_mark: C-left }
      ALT_L-f: { with_mark: C-right }
      # Forward/Backward Paragraph
      ALT_L-p: { with_mark: C-up }
      ALT_L-n: { with_mark: C-down }
      # Beginning/End of file
      ALT_L-comma: { with_mark: C-home }
      ALT_L-dot: { with_mark: C-end }
      # Page up/down
      ALT_L-v: { with_mark: pageup }
      CapsLock-v: { with_mark: pagedown }
      # folowing reset marks
      # Copy
      CapsLock-w: [C-x, { set_mark: false }]
      ALT_L-w: [C-c, { set_mark: false }]
      CapsLock-y: [C-v, { set_mark: false }]
      # Delete Forward/Backward character
      CapsLock-d: [delete, { set_mark: false }]
      CapsLock-h: [BACKSPACE, { set_mark: false }]
      # Delete Forward/Backward word
      ALT_L-d: [C-delete, { set_mark: false }]
      ALT_L-h: [C-BACKSPACE, { set_mark: false }]
      # Kill before line
      CapsLock-u: [Shift-home, C-x, { set_mark: false }]
      # Kill after line
      CapsLock-k: [Shift-end, C-x, { set_mark: false }]
      # transpose characters
      CapsLock-t: [Shift-left, C-x, right, C-v, {set_mark: false}]
      ALT_L-t: [Shift-right, C-x, left, C-v, left, {set_mark: false}]
      # Undo
      CapsLock-slash: [C-z, { set_mark: false }]

      # Newline
      # CapsLock-m: enter
      CapsLock-j: enter
      # Openline
      CapsLock-o: [end, enter]
      # C-Shift-ro: C-z
      # Search
      CapsLock-s: F3
      CapsLock-r: Shift-F3
      # M-Shift-5: C-h

      # Kill buffer
      CapsLock-q: [C-f4, { set_mark: false }]

      # Cancel
      KEY_ESC: [KEY_ESC, { set_mark: false }]

      # keybindings for flameshot
      KEY_F3: 
        launch: ["flameshot", "gui", "--clipboard", "-s"]
      CTRL_L-KEY_F3: 
        launch: ["flameshot", "gui", "--clipboard"]
      KEY_F4: 
        launch: ["flameshot", "gui", "--clipboard", "--pin", "-s"]
      CTRL_L-KEY_F4: 
        launch: ["flameshot", "gui", "--clipboard", "--pin"]
      mode: mark
        CapsLock-space: [{ set_mark: false }, {set_mode: no_mark} ]
      mode: no_mark
        CapsLock-space: [{ set_mark: true }, {set_mode: mark}]
      default_mode: no_mark

```
also give errors:
```
✗ /opt/xremap/xremap-x11 ~/.xremap
Error: Failed to load config '/home/yun/.xremap': keymap[0].remap: data did not match any variant of untagged enum Actions at line 14 column 7
```

**Comment by Yunuuuu** [comment]
Hi, @k0kubun , Thanks for your great help! I finally make it work by following config:
```
# https://github.com/k0kubun/xremap/blob/master/example/emacs.yml
# echo $XDG_SESSION_TYPE
keypress_delay_ms: 10

virtual_modifiers:
  - CapsLock

default_mode: no_mark

keymap:
  - name: Emacs
    exact_match: true
    remap:
      # following use marks
      # Cursor
      CapsLock-b: { with_mark: left }
      CapsLock-f: { with_mark: right }
      CapsLock-p: { with_mark: up }
      CapsLock-n: { with_mark: down }
      # Beginning/End of line
      CapsLock-a: { with_mark: home }
      CapsLock-e: { with_mark: end }
      # Forward/Backward word
      ALT_L-b: { with_mark: C-left }
      ALT_L-f: { with_mark: C-right }
      # Forward/Backward Paragraph
      ALT_L-p: { with_mark: C-up }
      ALT_L-n: { with_mark: C-down }
      # Beginning/End of file
      ALT_L-comma: { with_mark: C-home }
      ALT_L-dot: { with_mark: C-end }
      # Page up/down
      ALT_L-v: { with_mark: pageup }
      CapsLock-v: { with_mark: pagedown }

      # folowing reset marks
      # Copy
      CapsLock-w: [C-x, { set_mark: false }, { set_mode: no_mark }]
      ALT_L-w: [C-c, { set_mark: false }, { set_mode: no_mark }]
      CapsLock-y: [C-v, { set_mark: false }, { set_mode: no_mark }]
      # Delete Forward/Backward character
      CapsLock-d: [delete, { set_mark: false }, { set_mode: no_mark }]
      CapsLock-h: [BACKSPACE, { set_mark: false }, { set_mode: no_mark }]
      # Delete Forward/Backward word
      ALT_L-d: [C-delete, { set_mark: false }, { set_mode: no_mark }]
      ALT_L-h: [C-BACKSPACE, { set_mark: false }, { set_mode: no_mark }]
      # Kill before line
      CapsLock-u: [Shift-home, C-x, { set_mark: false }, { set_mode: no_mark }]
      # Kill after line
      CapsLock-k: [Shift-end, C-x, { set_mark: false }, { set_mode: no_mark }]
      # transpose characters
      CapsLock-t: [Shift-left, C-x, right, C-v, { set_mark: false }, { set_mode: no_mark }]
      ALT_L-t: [Shift-right, C-x, left, C-v, left, { set_mark: false }, { set_mode: no_mark }]
      # Undo
      CapsLock-slash: [C-z, { set_mark: false }, { set_mode: no_mark }]

      # Newline
      # CapsLock-m: enter
      CapsLock-j: enter
      # Openline
      CapsLock-o: [end, enter]
      # C-Shift-ro: C-z
      # Search
      CapsLock-s: F3
      CapsLock-r: Shift-F3
      # M-Shift-5: C-h

      # Kill buffer
      CapsLock-q: [C-f4, { set_mark: false }, { set_mode: no_mark }]

      # keybindings for flameshot
      KEY_F3: 
        launch: ["flameshot", "gui", "--clipboard", "-s"]
      CTRL_L-KEY_F3: 
        launch: ["flameshot", "gui", "--clipboard"]
      KEY_F4: 
        launch: ["flameshot", "gui", "--clipboard", "--pin", "-s"]
      CTRL_L-KEY_F4: 
        launch: ["flameshot", "gui", "--clipboard", "--pin"]
  - mode: mark
    exact_match: true
    remap:
      CapsLock-space: [{ set_mark: false }, { set_mode: no_mark }]
  - mode: no_mark
    exact_match: true
    remap:
      CapsLock-space: [{ set_mark: true }, { set_mode: mark }]

```
