### ISSUE TITLE
Double of the same key press

### ISSUE THREAD

**Issue by codeluggage** [k0kubun/xremap#273]
Hi - thank you A TON for making this, it is very much appreciated! 

I am trying to have a single press of `Esc` (or in my case `Ctrl_L`) turn into two `Esc` in one specific application. The first key press to close a suggestion pop up, and the second key press to exit insert mode. 

I've tried this both as part of `keyremap` and `modremap`, with and without `application:` limiting, but can't quite seem to make one modifier key press turn into two `Esc`. Here are some of the things I've tried, including an attempt to mix up the two `Esc` presses by having one be `Shift-Esc` and the other be a regular `Esc`. 

Does anyone have any advice on how to make `Esc` trigger twice?

_Note: I'm leaving in several of my attempts in the config below. I've tried them one by one and in various combinations._

```
modmap:
  - name: Global
    application:
      not: /obsidian/
    remap:
      CapsLock: Ctrl_L
      Ctrl_L: Esc
      # Mac keyboard swapping keys
      Alt_L: Win_L
      Win_L: Alt_L
      Alt_R: Win_R
      Win_R: Alt_R

  - name: Obsidian
    application:
      only: /obsidian/
    remap:
      CapsLock: Ctrl_L
      Ctrl_L: [Shift-Esc, Esc]
      # Mac keyboard swapping keys
      Alt_L: Win_L
      Win_L: Alt_L
      Alt_R: Win_R
      Win_R: Alt_R


keymap:
  - name: Default
    remap:
      # Emacs basic
      Win-b: C-b
      C-b: left
      Win-f: C-f
      C-f: right
      Win-p: C-p
      C-p: up
      Win-n: C-n
      C-n: down

      # Emacs word
      Alt-b: C-left
      Alt-f: C-right

      # Emacs lines
      Win-a: C-a
      C-a: home

      Win-e: C-e
      C-e: end

      Win-z: C-z
      Win-x: C-x
      Win-c: C-c
      Win-v: C-v
      Win-t: C-t
      Win-l: C-l
      Win-h: C-h
      Win-o: C-o
      Win-s: C-s
      Win-q: Alt-F4

  - name: Code specific
    application:
      not: [gnome-terminal-server.Gnome-terminal, code.Code]
    remap:
      Win-w: C-w
      C-w: [C-Shift-left, delete]

      Win-k: C-k
      C-k: [Shift-end, backspace]
      Win-d: C-delete

      C-u: [Shift-home, delete]

  - name: Obsidian
    application:
      only: /obsidian/
    remap:
      Ctrl_L: [Esc, Esc]
```

**Comment by k0kubun** [comment]
> I am trying to have a single press of Esc (or in my case Ctrl_L) turn into two Esc in one specific application.

Remapping a modifier is supported only in `modmap` because, in `keymap`, it also needs to serve as a modifier for combination presses. However, only `keymap` supports triggering multiple key presses since `modmap` is a key-level swap.

A possible workaround is you could remap `Ctrl_L` to a key that doesn't exist on your keyboard in `modmap` and then let it trigger Esc twice in `keymap`. e.g.

```yml
modmap:
  - remap:
      Esc: KatakanaHiragana
keymap:
  - remap:
      KatakanaHiragana: [Esc, Esc]
```

`KatakanaHiragana` is a random key that I assume doesn't exist on your keyboard, but you can use anything else.
