### ISSUE TITLE
Some mappings don't work on first launch of xremap

### ISSUE THREAD

**Issue by BvngeeCord** [k0kubun/xremap#281]
Hey! I'm using a systemd user service to start xremap. I have it bound to `default.target` (pre-graphical environment) as I would like to have my Caps->Esc bindings and some others available while still in the tty. However, while this works, when I launch the graphical environment (Hyprland in this case), I notice that some remaps do not work yet. Typing a simple `systemctl --user restart xremap.service` fixes them. Is there any reason that starting xremap at that early stage would possibly stop some of the remaps from working? Thanks.

Here is my systemd user service:
```
[Unit]
Description=Fast and cross-platform key remapper for linux

[Service]
Type=simple
ExecStart=/usr/bin/xremap --watch=device /home/jack/.config/xremap/xremap.yml --device "Glorious GMMK Pro" --device "Glorious GMMK Numpad"

[Install]
WantedBy=default.target

```
And my xremap config:
```
modmap:
  - name: Capslock to Escape
    remap:
      Capslock: Esc


keymap:
  - name: Application Hotkeys # (terminal hotkey is handled in hyprland.conf for safety reasons)
    remap:
      Super-w:
        launch: ["firefox"]
      Super-e:
        launch: ["kitty"] #update with a proper FM later

  - name: Rofi Scripts
    remap:
      Super-Space:
        launch: ["/home/jack/.config/xremap/scripts/rofi_menus.sh", "drun"]
      Super-Shift-e:
        launch: ["/home/jack/.config/xremap/scripts/rofi_menus.sh", "emoji"]
      Super-c:
        launch: ["/home/jack/.config/xremap/scripts/rofi_menus.sh", "cliphist"]
      Super-Tab:
        launch: ["/home/jack/.config/xremap/scripts/rofi_menus.sh", "window"]

  - name: Other Scripts
    remap:
      SYSRQ: # (Print equivalent)
        launch: ["/home/jack/.config/xremap/scripts/screenshot_select.sh"]
      Control-SYSRQ:
        launch: ["/home/jack/.config/xremap/scripts/screenshot_monitors.sh"]

  - name: Media Controls
    remap:
      Alt-F5:
        launch: ["playerctl", "previous"]
      Alt-F6:
        launch: ["playerctl", "next"]
      Alt-F7:
        launch: ["playerctl", "play-pause"]

      VolumeUp:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%+"] 
      Shift-VolumeUp:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "1%+"] 
      VolumeDown:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-"] 
      Shift-VolumeDown:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "1%-"] 
      Mute:
        launch: ["wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle"]

      Alt-VolumeUp:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SOURCE@", "5%+"] 
      Alt-Shift-VolumeUp:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SOURCE@", "1%+"] 
      Alt-VolumeDown:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SOURCE@", "5%-"] 
      Alt-Shift-VolumeDown:
        launch: ["wpctl", "set-volume", "@DEFAULT_AUDIO_SOURCE@", "1%-"] 
      Alt-Mute:
        launch: ["wpctl", "set-mute", "@DEFAULT_AUDIO_SOURCE@", "toggle"]
```
Specifically, I think the only thing that works before restarting it is the Caps->Esc modmap.
