### ISSUE TITLE
Held Alone remap not working as presented in README and there is no example in the sample config to show working behavior..

### ISSUE THREAD

**Issue by jeremyjjbrown** [k0kubun/xremap#290]
It seams like Alone Hold does not work, but I am not able to verify if I am configuring it as intended.

My end goal is to remap CapsLock to Esc if tapped and to vim movements if held in combo with hjkl. I have created this key mapping before in QMK, Karbiner, AutoHotKey and xmodmap. Now I am moving to Sway so I wanted to try xremap for it's application specific functionality.

My last attempt looked like this:
```
modmap:
  - name: Caps Esc
    remap: # Required
      CapsLock:
        held: Super # Required
        alone: Esc # Required

keymap:
  - remap:
      Super-h: Left
      Super-j: Down
      Super-k: Up
      Super-l: Right
```

It wouldn't be my preferred solution to involve Super, but really nothing I have attempted for movements has worked. Any corrections to what I have here, or an example in the sample config would be very appreciated.
