### ISSUE TITLE
Alt remaps do not work on GTK apps on GNOME under Wayland.

### ISSUE THREAD

**Issue by denysonique** [k0kubun/xremap#294]
When using the simple below example config Xremap does not perform the select all action on Gedit. 
In the same GNOME session it works for Kate under XWayland.
For KDE Wayland it also works with no problem.

```yaml
keymap:
  - name: Emacs bindings
    remap:
      M-a: C-a

```

gnome-shell: 42.5
Kernel: 5.19.0-41-generic #42~22.04.1-Ubuntu
