### ISSUE TITLE
Cinnamon Ctrl-Tab issues

### ISSUE THREAD

**Issue by kaidadragonfly** [k0kubun/xremap#309]
Under Cinnamon if I swap Ctrl and Super and then want to make Ctrl-Tab behave as Super-tab it doesn't work.  

Instead of getting the Cinnamon window switcher (that I have bound to Super-tab) it just switches the window (but doesn't update keyboard settings).

**Comment by kaidadragonfly** [comment]
My config file:
```
modmap:
  - name: Global
    application:
      not: firefox
    remap:
      Capslock: Ctrl_L
  - name: Firefox
    application:
      only: firefox
    remap:
      Super_L: Ctrl_L
      Super_R: Ctrl_R
      Ctrl_L: Super_L
      Capslock: Super_L

keymap:
  - name: Global
    application:
      not: [Gnome-terminal, Guake, firefox]
    remap:
      Super-a: C-a
      Super-b: C-b
      Super-c: C-c
      Super-d: C-d
      Super-e: C-e
      Super-f: C-f
      Super-g: C-g
      Super-h: C-h
      Super-i: C-i
      Super-j: C-j
      Super-k: C-k
      Super-l: C-l
      Super-m: C-m
      Super-n: C-n
      Super-o: C-o
      Super-p: C-p
      Super-q: C-q
      Super-r: C-r
      Super-s: C-s
      Super-t: C-t
      Super-u: C-u
      Super-v: C-v
      Super-w: C-w
      Super-x: C-x
      Super-y: C-y
      Super-z: C-z
      
  - name: Firefox
    application:
      only: firefox
    remap:
      Ctrl-1: M-1
      Ctrl-2: M-2
      Ctrl-3: M-3
      Ctrl-4: M-4
      Ctrl-5: M-5
      Ctrl-6: M-6
      Ctrl-7: M-7
      Ctrl-8: M-8
      Ctrl-9: M-9
      Ctrl-tab: Super-tab
      Super-tab: C-tab
```
