### ISSUE TITLE
Key press / release is too fast for emacs on hyprland(wayland)

### ISSUE THREAD

**Issue by jixiuf** [k0kubun/xremap#340]
```
keypress_delay_ms: 10
keymap:
  - name: Emacs
    application:
      only: [emacs,Emacs]
    remap:
    # switch to english language and send C-g
      C-g: [super-Space,C-g]
```
same to #179 but for emacs with wayland  (hyprland)

I found that adding a tiny sleep here makes it work:
```
diff --git a/src/event_handler.rs b/src/event_handler.rs
index 30ff952..9568ddd 100644
--- a/src/event_handler.rs
+++ b/src/event_handler.rs
@@ -527,6 +527,7 @@ impl EventHandler {
 
         // Resurrect the original modifiers
         self.send_keys(&extra_modifiers, PRESS);
+        self.send_action(Action::Delay(self.keypress_delay));
         self.send_keys(&missing_modifiers, RELEASE);
     }
 
```
