### ISSUE TITLE
[feature request] implimenting reference in Yaml config  

### ISSUE THREAD

**Issue by Vaisakhkm2625** [k0kubun/xremap#359]
in yaml, there is way to name and reference back a config

```yaml

mymap: &mymap
      C-b: left
      C-f: right
      C-p: up
      C-n: down


keymap:
  - name: Emacs binding
    application:
      only: Slack
    remap:
       *mymap
     
```

https://stackoverflow.com/questions/2063616/how-to-reference-a-yaml-setting-from-elsewhere-in-the-same-yaml-file

But it seems like this feature of yaml is not supported in xremap.. 
```yaml
super-d: &id1
  launch: ["firefox"]
keymap:
  - name: general keys
    remap: *id1

```
```sh


❯ xremap .config/xremap/config.yml --watch=config
Error: Failed to load config '.config/xremap/config.yml': unknown field `super-d`, expected one of `modmap`, `keymap`, `default_mode`, `virtual_modifiers`, `keypress_delay_ms`

```
but it would be nice to have... but in order to support this.. we need to ignore the values those other than what defined by xremap... 
ignoring the values would help to  make other applications to store values in the same file (like a yaml generator ui for xremap)

So will this be possible to implement  ?

**Comment by k0kubun** [comment]
> in yaml, there is way to name and reference back a config
> But it seems like this feature of yaml is not supported in xremap..

`serde_yaml` (xremap's YAML deserializer) seems to support YAML aliases. I tested it on xremap and worked fine.

> it would be nice to have... but in order to support this.. we need to ignore the values those other than what defined by xremap...
> ignoring the values would help to make other applications to store values in the same file (like a yaml generator ui for xremap)
> 
> So will this be possible to implement ?

We probably can't just accept random keys anywhere like you suggested. It would break validation, so it would bring inconvenience as well. You have to put entries in the correct scope and then alias it somewhere else, no matter what.

This is what you can do instead:

```yml
keymap:
  - name: mymap
    application:
      only: [] # ignore this entry and use this only for aliasing
    remap: &mymap
      C-b: left
      C-f: right
      C-p: up
      C-n: down
  - name: Emacs binding
    application:
      only: Slack
    remap:
       *mymap
```
