### ISSUE TITLE
Unable to remap just modifier keys

### ISSUE THREAD

**Issue by debonet** [k0kubun/xremap#37]
Trying to remap all instances of modifier keys (in this case swapping Alt_L for Control_L within Chrome to emulate an Apple Mac experience):

config:

~~~
window class_only: 'google-chrome' do
	remap 'Meta_L', to: 'Control_L'
end
~~~

Result:

~~~

remapped for class: "google-chrome"
Handler not found!: [25, 64, {133=>{0=>#<Proc:0x55bf09b7d090@/home/jsd/xremap/mrblib/xremap/key_remap_compiler.rb:30>}, 25=>{}}]

~~~

**Comment by k0kubun** [comment]
For some reason, the document didn't mention it, but it's currently out of scope by xremap (since modifier keys alone don't trigger X events) and you'd need to also use some other tools like xmodmap for that purpose.

**Comment by debonet** [comment]
I see.

Is there a way to catch mouse events, so for example, Meta-Mouse0 could get remapped to Control-Mouse0?

**Comment by k0kubun** [comment]
If it's supported by Xlib, it might work, but for now I'm not sure.

**Comment by k0kubun** [comment]
We supported both in xremap 0.1.0+. We changed the config structure, and what you need would look something like:

> swapping Alt_L for Control_L within Chrome

```yml
modmap:
  - name: Emulate an Apple Mac
    remap:
      Super_L: Control_L
    application:
      only: Google-chrome
```

> Meta-Mouse0 could get remapped to Control-Mouse0

Please follow the instructions in https://github.com/k0kubun/xremap/issues/44#issuecomment-1001073551 to specify `--device` options for the mouse and the keyboard. Then what you requested would look like:

```yml
keymap:
  - name: Mouse remapping
    remap:
      M-BTN_LEFT: C-BTN_LEFT
    application:
      only: Google-chrome
```

I hope the latest xremap has all you need.
