### ISSUE TITLE
Key sequences are broken

### ISSUE THREAD

**Issue by xpusostomos** [k0kubun/xremap#373]
Consider the following config file:
```
keymap:                                                                                                                                                       
  - name: not-emacs                                                                                                                                           
    remap:                                                                                                                                                    
      C-x:                                                                                                                                                    
        remap:                                                                                                                                                
          KEY_5:                                                                                                                                              
            remap:                                                                                                                                            
              KEY_0: M-F4                           
```

This is designed to make the emacs close-window key sequence, aka C-x 5 0 close any window in KDE.  That works. HOWEVER, now when I run emacs in konsole, no key sequences that start with C-x work anymore. For example C-x C-s (save file) in emacs running in konsole doesn't work anymore. (Instead it runs search, the C-s emacs function)

Now I get it... when xremap sees C-x in console, it holds onto it, because it doesn't know if you are now going to type 5 0, or if you are going to type s, BUT.... it seems to me that once it sees a sequence it wasn't told to steal, such as "C-s" in this case, it should release the whole sequence for the underlying app to process. Thus allowing you to remap C-x 5 0, while still allowing C-x C-s to continue working.

i.e. you type:
C-x (xremap steals it)
C-s (xremap releases C-x C-s)

or

you type:
C-x (xremap steals it)
5 (xremap steals it)
0 (xremap does its remap)

How to implement it? Either you could just make this the standard behavior, or you could have a default clause, and a default action:

```
keymap:                                                                                                                                                       
  - name: not-emacs                                                                                                                                           
    remap:                                                                                                                                                    
      C-x:                                                                                                                                                    
        remap:                                                                                                                                                
          KEY_5:                                                                                                                                              
            remap:                                                                                                                                            
              KEY_0: M-F4             
        default: emit-previous-sequence              
```
