### ISSUE TITLE
Allow Press/Release on Held and Alone actions

### ISSUE THREAD

**Issue by cat-phish** [k0kubun/xremap#379]
Maybe I'm missing something, but the program doesn't currently seem to support separate press and release actions to be nested underneath held and alone actions. The specific functionality I'm trying to implement in my config is if Capslock is held, send F9 on the press and send F9 again on the release. And if Capslock is just pressed and not held just send F9 once. Here are the lines from my config:

```
keymap:
  - name: Wezterm
    application:
      only: org.wezfurlong.wezterm.org.wezfurlong.wezterm
    remap:
      Capslock:
        held:
          press: F9
          release: F9
        alone: F9
        alone_timeout_millis: 200
```
This gives me the error:
`Error: Failed to load config '.config/xremap/test.yaml': modmap[0].remap: data did not match any variant of untagged enum ModmapAction at line 6 column 7`

Not sure if I'm doing something wrong in the syntax, but it seems like it's not currently supported and would be a nice feature to implement.
