### ISSUE TITLE
Right and Left alt key do not work together

### ISSUE THREAD

**Issue by hakan-demirli** [k0kubun/xremap#387]
I can use Key_9 and Key_1. But when I hold them together and press m, Key_8 do not trigger.

```yml
keymap:
  - name: Default
    remap:
      KEY_RIGHTALT-m: KEY_1
      KEY_LEFTALT-m: KEY_9
      KEY_RIGHTALT-KEY_LEFTALT-m: KEY_8
```

**Comment by k0kubun** [comment]
I think it's fair to fix the behavior. I'm open to merging a pull request to fix it.

In the meantime, using `exact_match` in that entry might be useful as a workaround. Have you tried it?

**Comment by hakan-demirli** [comment]
I have just tried the following and it also didn't work.
```yaml
keymap:
  - name: Default
    exact_match: true
    remap:
      KEY_RIGHTALT-m: KEY_1
      KEY_LEFTALT-m: KEY_2
      KEY_LEFTALT-KEY_RIGHTALT-m: KEY_3
```
I have also tried the modmap like the example given in the README. But, it complained: ```unknown field `exact_match`, expected one of `name`, `remap`, `application`, `device` at line 15 column 5```
```yaml
modmap:
  - name: Default
    exact_match: true
    remap:
      KEY_RIGHTALT-m: KEY_1
      KEY_LEFTALT-m: KEY_2
      KEY_LEFTALT-KEY_RIGHTALT-m: KEY_3
```

I would love to create a PR but I don't know rust. I will probably learn rust in couple of months since there are quite a lot of open source projects I daily drive which use rust. Until then I can workaround the bug by using a QMK capable keyboard together with xremap.

**Comment by k0kubun** [comment]
Hmmmm. Interesting. How about this?

```yml
keymap:
  - remap:
      KEY_LEFTALT-KEY_RIGHTALT-m: KEY_3
  - remap:
      KEY_RIGHTALT-m: KEY_1
      KEY_LEFTALT-m: KEY_2
```
