### ISSUE TITLE
application-specific modmap not working for KDE wayland

### ISSUE THREAD

**Issue by ydzhou** [k0kubun/xremap#393]
modmap applies to all applications and ignore my application specific config.

Here is the example config:
```
modmap:
  - name: OSX style binding
    remap:
      Win_L: Ctrl_L
      Win_R: Ctrl_R
    application:
      not: [google-chrome, kitty]
```

Google-chrome and Kitty still get applied with Win key swap

- xremap version: 0.8.12
- KDE: 5.27.10
- wayland: 1.22.0
- OS: Linux 6.6.7
