### ISSUE TITLE
Can we use `alone` and `held` in `keymap`?

### ISSUE THREAD

**Issue by Kabouik** [k0kubun/xremap#394]
I am trying to remap some special buttons on my devices that I assigned to `Shift+F1` and `Shift+F2`, respectively, using a Windows program the the manufacturer provides. The settings saved from that program persist even in Linux. Now, I would like each of these buttons to act differently depending on whether they are held or pressed quickly:

```
virtual_modifiers:
  - COMPOSE
modmap:
  - name: Thumb-chording-both-sides
    remap:
      # Menu -> Super
      COMPOSE: SUPER_L
      ALT_R: ALT_L
keymap:
  - name: L4-mouse-buttons
    remap:
      # L4 = Shift+F1 in WinControls (Windows), which persists in Linux -> LMB and RMB
      SHIFT-KEY_F1:
        alone: BTN_LEFT
        held: BTN_RIGHT
        alonetimeoutmillis: 500
  - name: R4-scroll
    remap:
      # R4 = Shift+F2 in WinControls (Windows), which persists in Linux -> scroll up and down
      SHIFT-KEY_F2:
        alone: KEY_SCROLLDOWN
        held: KEY_SCROLLUP
        alonetimeoutmillis: 500		
```

Unfortunately, `keymap` does not seem to support that. It works only if I put the replacement on the same line as the replaced combination, without specifying `alone`, `held`, and `alonetimeoutmillis`. Else, I'd get:

"Error: Failed to load config '/home/mat/.config/xremap/config.yml': keymap[0].remap: data did not match any variant of untagged enum Actions at line 13 column 7"

Is there a way to achieve what I want that I may have missed?

Thanks for this great program!

**Comment by k0kubun** [comment]
As you saw, we don't support `alone`/`held` in `keymap` at the moment. 

Have you tried using `alone`/`held` on `KEY_F1` and `KEY_F2` in `modmap`? Just emit the same key in `alone`, but emit another key in `held`, and then remap `SHIFT-[same key]` and `SHIFT-[another key]` to what you want respectively. Does that have any problem?

**Comment by Kabouik** [comment]
Good idea yes! Something like this works, except I see no action on SCROLLDOWN and SCROLLUP, but I assume it'sprobably a mistake on my side, I'll check the documentation again.

`` yml
virtual_modifiers:
  - COMPOSE
modmap:
  - name: Thumb-chording-on-both-sides
    remap:
      # Menu -> Super
      COMPOSE: SUPER_L
      # Alt_R -> Alt_L for Emacs
      ALT_R: ALT_L
  - name: L4-mouse-buttons_part1
    remap:
      # L4 = Shift+F1 in WinControls (Windows), which persists in Linux -> LMB and RMB
      # modmap supports alone/held attributes, but not modmap, so we first assign held/alone attributes
      # to F! and F2, and then we will add the modifier to the resulting 4 actions in modmap
      KEY_F1:
        alone: KEY_F1
        held: KEY_F3
        alonetimeoutmillis: 800
  - name: R4-scroll_part1
    remap:
      # R4 = Shift+F2 in WinControls (Windows), which persists in Linux -> scroll up and down
      # modmap supports alone/held attributes, but not modmap, so we first assign held/alone attributes
      # to F! and F2, and then we will add the modifier to the resulting 4 actions in modmap
      KEY_F2:
        alone: KEY_F2
        held: KEY_F4
        alonetimeoutmillis: 800
keymap:
  - name: L4_R4_part2
    remap:
      # Add the modifier to the combination replacement set in part1
      SHIFT-KEY_F1: BTN_LEFT
      SHIFT-KEY_F2: KEY_SCROLLDOWN 
      SHIFT-KEY_F3: BTN_RIGHT
      SHIFT-KEY_F4: KEY_SCROLLUP
```

**Comment by Kabouik** [comment]
Trying to simplify my configuration, after I realized I didn't even need the Compose/Super mapping since the same can be done in Sway using `xkb_options altwin:menu_win`. I also changed my mind about the alone/held requirement because this would prevent me from holding LMB to select text or drag.

```yml
modmap:
  - name: Thumb-chording-on-both-sides - Menu-to-Super and RAlt-to-LAlt
    remap:
      # Alt_R -> Alt_L for Emacs
      ALT_R: ALT_L
keymap:
  - name: Thumb-chording-on-both-sides - R4-to-FN
    remap:
      # R4 set to ScrollLock in GPD's WinControl app for Windows (persists in Linux) -> FN
      KEY_SCROLLLOCK: KEY_FN
  - name: L4-to-LMB-and-RMB
    remap:
      # L4 set to Shift+F1 in GPD's WinControl app for Windows (persists in Linux) -> LMB and RMB
      SHIFT-KEY_F1: BTN_LEFT
      FN-SHIFT-KEY_F1: BTN_RIGHT
```

The FN parts are not tested yet, not sure I can add it as a modifier in `keymap` just like that. In any case, I probably still need `keymap` because my buttons are hw-bound to modifier+key, so I'ill still have the #127 issue.
