### ISSUE TITLE
[keymap] application only filter does not work on Sway

### ISSUE THREAD

**Issue by acro5piano** [k0kubun/xremap#40]
First of all, thank you for the great library! I'm a big fan of Xremap and using it for over five years. It significantly improves my productivity in my daily Linux life!

# Problem

application only filter seems not work on Sway WM.

- expected: Xremap is applied to specific windows
- actual: Xremap is not applied to any windows

# Versions

- Xremap 0.1.0
- `Linux archlinux 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux`
- sway version 1.6.1

# Config

```yml
keymap:
  - name: Emacs binding
    application:
      only: 
        - brave-browser # wayland Brave
        - Brave-browser # xwayland Brave
        - chromium      # wayland Chromium
    remap:
      C-b: left
      C-f: right
      C-p: up
      C-n: down
```

And run

```
sudo ./Downloads/xremap .xremap.yml --device /dev/input/event4
```

(I disabled all other software like xremap(ruby), wayremap, and XKeysnail)

# What I tried

### To see whether xremap supports Xwayland or not, launch Brave in Walyand mode

```
brave --enable-features=UseOzonePlatform --ozone-platform=wayland
```

Result: Not works

### How about Chromium ?

```
chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
```

Result: Not works

# Other notes

To see Window Class and App ID in Sway, the following command is useful:

```
swaymsg --type subscribe --monitor '["window"]' | jq -r '.. | select(.focused?) | [.app_id, .window_properties.class] | @tsv'
```
