### ISSUE TITLE
can deny_unknown_fields in config parser (serde_yaml) be removed?

### ISSUE THREAD

**Issue by Pieterv24** [k0kubun/xremap#401]
I've noticed the use of `#[serde(deny_unknown_fields)]`on the structs that are used to parse the config.

Is there any usecase/reason for this?

If not, I would like to propose removing these attributes.
This would allow the use of Anchors and Aliases (as per the [yml spec](https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases))

When using the following config
```yaml
terminals: &terminals
  - kitty
  - xterm
  - gnome-terminal
  - etc
 
modmap:
  - name: Terminals
    application:
      only: *terminals
    remap:
      Alt_L: Ctrl_R
```

An error is thrown by the serde deserialiser because `terminals` is an unknown field.

If there is no usecase for these attributes, I would like to propose their removal.
(I could create a PR for this if needed)
