### ISSUE TITLE
Swap caps and esc while using caps as a virtual modifier

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [k0kubun/xremap#408]
I'm trying to do something like this but this is resulting in esc not working at all:
```
virtual_modifiers:
  - CapsLock
modmap:
  - remap:
      CapsLock:
        held: CapsLock
        alone: Esc
      Esc: CapsLock
keymap:
  - name: Global
    remap:
      CapsLock-i: Up
      CapsLock-j: Left
      CapsLock-k: Down
      CapsLock-l: Right
```
