### ISSUE TITLE
Distinguish between physical keypresses and remapped keypresses

### ISSUE THREAD

**Issue by musjj** [k0kubun/xremap#417]
In my config, I remapped `CapsLock: Esc` in my `modmap` and `Esc: Grave` in my `keymap`. I have a 60% keyboard and this mapping allows me to insert a `~`/`` ` `` without holding down a gajillion of modifier keys.

But this effectively remaps `CapsLock` to `Grave`, because xremap fails to distinguish between physical keypresses and keypresses from remaps.

In my `interception-tools` config (combining `dual-function-keys` and `interception-k2k`), this kind of mapping works perfectly. Can this use-case also be supported in xremap?

**Comment by musjj** [comment]
Never mind, I'm dumb. This work if I put my `Esc: Grave` together in `modmap` instead of `keymap`.

<details>
<summary><b>Config for reference</b></summary>

```yaml
modmap:
  - remap:
      CapsLock:
        alone:
          - Esc
        alone_timeout_millis: 300
        held:
          - Ctrl_L
      Enter:
        alone:
          - Enter
        alone_timeout_millis: 300
        held:
          - Alt_L
      Esc: Grave
```
</summary>
