### ISSUE TITLE
Doesn't work in PICO-8 games

### ISSUE THREAD

**Issue by musjj** [k0kubun/xremap#419]
I tried to remap my `WSAD` keys to directional keys and it works everywhere except in PICO-8 in-browser games: https://www.lexaloffle.com/pico-8.php. It's really bizzare, because the mapping works in other web pages and the browser's UI itself, but it doesn't work inside the game.

Previously, I was using [`interception-tools`](https://wiki.archlinux.org/title/interception-tools) with [`interception-k2k`](https://github.com/zsugabubus/interception-k2k) and it worked just fine. Strangely, both `interception-tools` and `xremap` uses `evdev` and `uinput`, so I'm not sure why it's not working with `xremap`.

My config:

```yaml
keypress_delay_ms: 25
keymap:
  - remap:
      w: Up
      s: Down
      a: Left
      d: Right
      j: z
      k: x
```

I'm also having the same stuttering problem mentioned in the other issue: https://github.com/k0kubun/xremap/issues/268#issuecomment-1487261282

My `keypress_delay_ms` is already set to the same value of my Hyprland config's `repeat_rate`, but it's still stuttering.
