### ISSUE TITLE
Remap CapsLock to semicolon in modmap

### ISSUE THREAD

**Issue by pchabros** [k0kubun/xremap#434]
I can remap CapsLock to semicolon in keymap with this:

```
keymap:
  remap:
    CapsLock: Shift-Semicolon
```

But I want also to remap CapsLock to CTRL when held. I tried this:

```
modmap:
  remap:
    CapsLock:
      held: Shift-Semicolon
      alone: Ctrl_L
```
(also `Shift_L-Semicolon`) but both doesn't work.
