### ISSUE TITLE
xremap config not work as expected when use not: [...] and only: [...]

### ISSUE THREAD

**Issue by zw963** [k0kubun/xremap#435]
Following is a config example:

```yml
keymap:
  - name: Common but not Emacs, konsole, org.gnome.Nautilus etc.
    application:
      not:  [Emacs,emacs,konsole,Alacritty,foot,org.wezfurlong.wezterm,org.gnome.Nautilus]
   remap:
     C-e: { with_mark: end }
  - name: Beyond Compare 4
    application:
      only: [Bcompare4]
    remap:
      C-e: C-e
```

Above config, the keymap in the `not: [....]` override the keymap in the `only: [...]`, this is not expected, that is, even if current app class is Bcompare4, C-e always mapping to `end`.

The expected behavior is, if current app is Bcompare4, it should always mapping C-e -> C-e instead, whatever it defined after/before the not.

Thanks.

---------------------

BTW: above work as expected if move beyond compare config before another.
