### ISSUE TITLE
Mapping Ctrl_R to Ctrl+w

### ISSUE THREAD

**Issue by vikasrawal** [k0kubun/xremap#60]
I want to map right control key to Ctrl+w which is the default keybinding for closing the current tab in qutebrowser.

This is the config.yml file I am using.

```
keymap:
  - name: Right Control for Qutebrowser
    application:
      only: qutebrowser
    remap:
      Ctrl_R: Ctrl-w

```
I am not sure if I should use a modmap or a keymap for this.

If I use keymap, I get the error:

Failed to prepare an output device: Permission denied (os error 13) 

And if I use modmap, I get the error:

Failed to load config '/home/vikas/.config/xremap/config.yml': modmap[0].remap: data did not match any variant of untagged enum KeyAction at line 6 column 13

What is wrong?

**Comment by k0kubun** [comment]
> Failed to prepare an output device: Permission denied (os error 13)

It's irrelevant to the config. Did you follow https://github.com/k0kubun/xremap? Alternatively, you could also use `sudo xremap` to fix it.

> Failed to load config '/home/vikas/.config/xremap/config.yml': modmap[0].remap: data did not match any variant of untagged enum KeyAction at line 6 column 13

`modmap` is for key-to-key mapping, and `keymap` is for combination-to-combination mapping. Because `Ctrl-w` is a combination, you need to use `keymap`. The problem here is that the config supports remapping of modifier keys only in `modmap`.

As a workaround, something like this should work:

```yml
modmap:
  - application:
      only: qutebrowser
    remap:
      Ctrl_R: Muhenkan # choose whatever key your keyboard doesn't have and does no harm
keymap:
  - application:
      only: qutebrowser
    remap:
      Muhenkan: Ctrl-u
```

I assume this case is rare and xremap therefore doesn't support it directly, but let me know if you need to do the workaround in too many places.
