### ISSUE TITLE
modprobe shoud have uinput loaded

### ISSUE THREAD

**Issue by wvq** [k0kubun/xremap#71]
> Option 2: Run xremap without sudo.

On my Archlinux os, the `uinput` module not loaded in kernel, so the rules has no effects.

the solution is need add one step: 
```
sudo modprobe uinput
```

or 
Creating `/etc/modules-load.d/uinput.conf` with content and reboot:
```
uinput
```

**Comment by k0kubun** [comment]
Yup, that's needed for Arch Linux. Just to have more contexts for fixing the document, it's not specific to Option 2 but it's needed for Option 1 as well, right?

**Comment by k0kubun** [comment]
What you described in the description is correct. If you want README to be changed, please do so via pull requests. Thank you.

**Comment by wvq** [comment]
Sorry for the late reply.  

It's for Option 2: 
```bash
sudo gpasswd -a YOUR_USER input
echo 'KERNEL=="uinput", GROUP="input"' | sudo tee /etc/udev/rules.d/input.rules
```

the `uinput` not load, so the rule has no effects.

I'm not sure wether other linux distribution have same problem.

maybe you can put a tip to README, to help somebody (like me) use this tool,
As it's take me hours to solve this problem ：(

Just a example:

Tips:  If the `/etc/udev/rules.d/input.rules` has no effects, check the `uinput` module is loaded.
``` bash
# check if the uinput is loaded
lsmod | grep uinput

# load uinput module
sudo modprobe uinput
```

**Comment by k0kubun** [comment]
> It's for Option 2:
> the uinput not load, so the rule has no effects.

My point is that uinput is always used by xremap. So it should also impact Option 1 and it's probably not specific to Option 2 while it might seem like so when you touch udev.

> maybe you can put a tip to README, to help somebody (like me) use this tool,
> As it's take me hours to solve this problem ：(
> Tips: If the /etc/udev/rules.d/input.rules has no effects, check the uinput module is loaded.

Could you file the suggestion as a pull request?

**Comment by wvq** [comment]
Yes, I will do some test and pull a request later.

BTW, is there any plan to disable some keymapping.
   If I map `Alt-c: Ctrl-c`, I don't want `Ctrl-c` work any more , like :
  ```yml

remap:
  Alt-c: ^-Ctrl-c # use a letter ^ or something means replace the key Ctrl-c to Alt-c,
                  # if the key Ctrl-c if not mapping to something, it will has no effects.

  Ctrl-c: Nothing # or define the key do nothing

disable: # or define a disable array to disable some key
    - Ctrl-c 
  ```

I try to code this for me, as rust is my prepare to learn language, it may take a long time to finish it.
