### ISSUE TITLE
Is there a way to listen for the second keystroke with timeout?

### ISSUE THREAD

**Issue by 0x78logs** [k0kubun/xremap#80]
Hello,

I would like to implement something that's similiar to how
key mappings are handled in vim.

say for example I want to remap `jk` to escape
instead of pressing `jk` all at once I can press `j` first then I have
a short amount of milliseconds to follow with `k`

is there a way to implement this using **Xremap**? and if yes can I control the timeout too?
*If the second key isn't presessed within the given timeout, that should cancel the listening*
thank you.

**Comment by k0kubun** [comment]
In your use case, do you want to remap both j→k and k→j as escape? 

If you meant j→k only, the closest thing that currently exists would be:

```yml
keymap:
  - remap:
      J:
        remap:
          K: Esc
```

which always translates a key sequence j→k to escape. We could possibly extend this to something like:

```yml
keymap:
  - remap:
      J:
        remap:
          K: Esc
        timeout_millis: 500
```

which results in:

* input: j → 500ms+ wait → k
  * output: j, k
* input: j → 500ms- wait → k
  * output: escape

Is this what you want?
