### ISSUE TITLE
Remapping Alt_R behaves like Alt instead of AltGr

### ISSUE THREAD

**Issue by DidacGit** [k0kubun/xremap#90]
Hey! First of all thanks for the very useful package,

My issue is that I'm trying to map Print and Ctrl_R to Alt_R. For that I've tried:
```
modmap:
  - name: Global
    remap:
      Ctrl_R: Alt_R
      Print: Alt_R
```
and
```
modmap:
  - name: Global
    remap:
      Ctrl_R: Alt_R
      Print:
        held: Alt_R
        alone: Alt_R
```
And while Ctrl_R always gets correctly remapped, Print never does.
Am I missing something?
Thanks in advance

**Comment by k0kubun** [comment]
Can you try starting xremap like `RUST_LOG=debug xremap config.yml` and share logs that are printed when you press a Print key? I suspect it might not be `KEY_PRINT`.

**Comment by DidacGit** [comment]
Yay! Thanks a lot it turns out that my `Print` key (on a Thinkpad Wireless keyboard) is `Sysrq` instead. This now worked:
```
modmap:
  - name: Global
    remap:
      Ctrl_R: Alt_R
      Sysrq: Alt_R
```
Thanks a lot!
